sudo: required
language: clojure

jdk:
  - oraclejdk8

services:
  - docker

script:
  - docker run -d -p5672:5672 rabbitmq
  - lein midje

deploy:
  - provider: script
    skip_cleanup: true
    script: bash -c "lein change :deploy-repositories concat '[[\"releases\" {:url \"https://clojars.org/repo/\" :username :env :password :env}]]'  && lein deploy releases"
    on:
      tags: true
